name: Auto Save

on:
  schedule:
    - cron: '30 9 * * 1,4'
  workflow_dispatch:

jobs:
  auto-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests

      - name: Run Python script
        env:
          SAVE_INFO: ${{ secrets.SAVE_INFO }}
          TEL_INFO: ${{ secrets.TEL_INFO }}

        run: python save.py
